// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPPrAeEtDNCP4m-zinej6jlzgpG7XcFHA',
    appId: '1:537971701870:android:6810c432e4cb10da828e7f',
    messagingSenderId: '537971701870',
    projectId: 'note-dd0cc',
    databaseURL: 'https://note-dd0cc-default-rtdb.firebaseio.com',
    storageBucket: 'note-dd0cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC72bfph2EN6K7w992ucsrIa4hQFuB0jEo',
    appId: '1:537971701870:ios:26352e13bec8e75f828e7f',
    messagingSenderId: '537971701870',
    projectId: 'note-dd0cc',
    databaseURL: 'https://note-dd0cc-default-rtdb.firebaseio.com',
    storageBucket: 'note-dd0cc.firebasestorage.app',
    androidClientId: '537971701870-3cp7a1nni9k0lbkdurollb4btaaq1n7r.apps.googleusercontent.com',
    iosClientId: '537971701870-1rsdth8eplvngiln2i8r4mptonujh7ml.apps.googleusercontent.com',
    iosBundleId: 'com.engromjanali.securenote',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE58Nbs8swoWM0wBmYQzxphpR8oYZS54c',
    appId: '1:537971701870:web:c496dbe3153d8093828e7f',
    messagingSenderId: '537971701870',
    projectId: 'note-dd0cc',
    authDomain: 'note-dd0cc.firebaseapp.com',
    databaseURL: 'https://note-dd0cc-default-rtdb.firebaseio.com',
    storageBucket: 'note-dd0cc.firebasestorage.app',
    measurementId: 'G-2CW6JG46YH',
  );

}